version: '3'
services:
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./api-specification-document/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      API_URL: openapi.yml
    ports:
      - "10000:8080"